config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :users, only: %i[show] do
    resources :dogs, only: %i[new create]
  end

  resources :chatrooms, only: %i[show index] do
    resources :messages, only: :create
  end

  resources :sniffs, only: %i[index update destroy] do
    resources :chatrooms, only: :create
  end

  resources :dogs, only: [:show, :update, :destroy] do
    resources :sniffs, only: %i[create]
  end

  resources :dogs, only: :edit
  resources :users, only: :show

  patch 'dogs/:id/toggle_ready_to_walk', to: 'dogs#toggle_ready_to_walk', as: 'dog_toggle_ready_to_walk'

  resources :dogs_park, only: %i[show new create]

  get "discover", to: "dogs#discover"


  resources :users, only: :show

  resources :parks, only: %i[index update create]

end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :user
  belongs_to :viewed_park, class_name: 'Park', optional: true
  has_many :dogs_parks, dependent: :destroy
  has_many :parks, through: :dogs_parks
  has_many :sniffs_as_sniffer, class_name: 'Sniff', foreign_key: :sniffer_id, dependent: :destroy
  has_many :sniffs_as_sniffed, class_name: 'Sniff', foreign_key: :sniffed_id, dependent: :destroy

  validates :name, presence: true
  validates :breed, presence: true
  validates :age, presence: true, numericality: true
  validates :bio, presence: true

  has_many_attached :photos
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def show
    @dog = Dog.find(params[:id])
    @sniff = Sniff.find_by(sniffer: current_user.dogs.first, sniffed: @dog)

    @sent_sniff = Sniff.find_by(sniffer: current_user.dogs.first, sniffed: @dog)
    @received_sniff = Sniff.find_by(sniffer: @dog, sniffed: @current_user.dogs.first)
  end

  def new
    @user = current_user
    @dog = Dog.new
  end

  def create
    @dog = Dog.new(dog_params)
    @dog.user = current_user
    park_id = params.require(:dog).permit(:park_ids)[:park_ids]
    park = Park.find(park_id)
    @dog.parks << park
    @dog.viewed_park = park
    if @dog.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def edit
    @dog = Dog.find(params[:id])
  end

  def update
    @dog = Dog.find(params[:id])
    if @dog.update(dog_params)
      # if request comes from user page, redirect to user show page, otherwise to home
      if params[:dog][:park_ids]
        redirect_to users_path
      else
        redirect_to root_path
      end
    else
      render 'pages/home'
    end
  end

  def destroy
    @dog = Dog.find(params[:id])
    @dog.destroy
    redirect_to root_path
  end

  def discover
    @dog = Dog.all.sample
  end

  def toggle_ready_to_walk
    @dog = Dog.find(params[:id])
    @dog.toggle! :ready_to_walk
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :breed, :age, :bio, :viewed_park_id, :park_ids, photos: [])
  end
end

app/views/dogs/discover.html.erb
<%= render 'shared/navbar-top' %>
<div style="margin-top: 5rem;" class="general-container">
  <h1 class="mb-4 text-left">Discover new buddies</h1>
  <div class="card-dog my-4">
    <div class="card-dog-photo-box mt-3" style="background-image: url(<%= cl_image_path @dog.photos.first.key, :transformation=>[
  {:height=>250, :gravity=>"auto", :crop=>"fill"}]%>); border-top-right-radius: 15px; border-top-left-radius: 15px;">
    </div>
    <div class="card-dog-content d-flex justify-content-between pt-2 pb-2">
      <div class="card-dog-content-info ml-3">
        <p class="medium">
          <%= @dog.name %>
        </p>
        <p>
          <%= @dog.breed %>,
          <%= @dog.age %>
        </p>
      </div>
      <%= link_to '', dog_path(@dog), class: "stretched-link" %>
      <div class="card-dog-content-tag d-flex align-items-end mr-3">
        <div class="status">
          <% if @dog.ready_to_walk %>
            <p class="medium">ready to walk</p>
          <% end %>
        </div>
      </div>
  </div>
  <div class="button_group_discover">
    <div class="button_group_discover_one">
    <%= link_to 'Sniff', dog_sniffs_path(@dog, referrer:"discover"), method: :post, id:'sniffer', class: "btn btn-secondary my-3" %>
    </div>
    <div class="button_group_discover_two">
    <%= link_to 'Bark', discover_path, class: "btn btn-secondary-revert mb-3", id: "woof" %>
    </div>
  </div>
</div>
<%= render 'shared/bottom-navbar' %>

app/views/dogs/edit.html.erb
<%= render 'shared/navbar-top' %>
<div style="margin-top: 5rem; margin-bottom: 5rem;" class="container">
<h1>Edit <%= @dog.name %>'s profile</h1>
<div class="around-the-form-edit">
  <%= simple_form_for @dog do |f| %>
  <%= f.input :name %>
  <%= f.input :breed %>
  <%= f.input :age %>
  <%= f.input :bio %>
  <div class="upload-btn-wrapper">
  <button class="btn btn-secondary ">Upload photo</button>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  </div>
  <%= f.submit "Update", class: "btn btn-secondary mb-3" %>
  <% end %>
  <%= link_to "Delete #{@dog.name}'s profile", dog_path(@dog),  method: :delete, class: "btn btn-secondary", id: "cancel" %>
</div>
</div>
<%= render 'shared/bottom-navbar' %>

app/views/dogs/new.html.erb
<%= render 'shared/navbar-top' %>
<div style="margin-top: 5rem;" class="container">
  <h1>Add the dog</h1>
  <%= simple_form_for [@user, @dog] do |f| %>
  <%= f.input :name %>
  <%= f.input :breed %>
  <%= f.input :age %>
  <%= f.association :parks, required: true, input_html: { multiple: false }, prompt: "Select a park" %>
  <%= f.input :bio %>
  <div class="upload-btn-wrapper">
    <button class="btn btn-secondary ">Now upload some photos</button>
    <%= f.input :photos, as: :file, input_html: { multiple: true }, required: true %>
  </div>
  <%= f.button :submit, "Done!", class: "btn btn-secondary mb-3" %>
  <% end %>
</div>

app/views/dogs/show.html.erb
<%= render 'shared/navbar-top-dog-profile' %>
<div style="margin-top: 62px; margin-bottom: 5rem;">
  <div class="dog-image banner">
    <%= render 'components/carousel_dog_show' %>
    <%= cl_image_tag @dog.user.photo.key, class: "avatar-xlarge " %>
    <div class="status">
      <% if @dog.ready_to_walk %>
        <p class="medium ">ready to walk</p>
      <% end %>
    </div>
  </div>
  <div class="general-container" style="margin-top: 65px;">
    <div class="dog-content">
      <div class="dog-content-title d-flex justify-content-between">
        <h2 class="mb-0">
          <%= @dog.name %>
        </h2>
      </div>
      <div class="dog-content-body">
        <div class="dog-content-body-info">
          <p class="mb-0" id="category">
            <%= @dog.breed %>, <%= @dog.age %>
          </p>
          <p class="mt-3">
            <%= @dog.bio %>
          </p>
        </div>
      </div>
      <div class="dog-content-sniff mb-3">
        <% if @sent_sniff %>
          <%= link_to 'Unsniff', sniff_path(@sent_sniff), method: :delete, id:'sniffer', class: "btn btn-secondary-revert" %>
        <% elsif @received_sniff && @received_sniff.status %>
          <%= link_to 'Unsniff', sniff_path(@received_sniff), method: :delete, id:'sniffer', class: "btn btn-secondary-revert" %>
        <% elsif @received_sniff && @received_sniff.status == nil %>
          <%= link_to 'Sniff back', sniff_path(@received_sniff), method: :patch, id:'sniffer', class: "btn btn-secondary" %>
        <% else %>
          <%= link_to 'Sniff', dog_sniffs_path(@dog), method: :post, id:'sniffer', class: "btn btn-secondary" %>
        <% end %>
      </div>
      <div class="dog-content-chat">
        <% if @sent_sniff && @sent_sniff.status %>
          <%= link_to 'Chat', chatroom_path(@sent_sniff.chatrooms.first), class: 'btn btn-primary' %>
        <% end %>
        <% if @received_sniff && @received_sniff.status %>
          <%= link_to 'Chat', chatroom_path(@received_sniff.chatrooms.first), class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
  <%= render 'shared/bottom-navbar' %>
</div>