config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :users, only: %i[show] do
    resources :dogs, only: %i[new create]
  end

  resources :chatrooms, only: %i[show index] do
    resources :messages, only: :create
  end

  resources :sniffs, only: %i[index update destroy] do
    resources :chatrooms, only: :create
  end

  resources :dogs, only: [:show, :update, :destroy] do
    resources :sniffs, only: %i[create]
  end

  resources :dogs, only: :edit
  resources :users, only: :show

  patch 'dogs/:id/toggle_ready_to_walk', to: 'dogs#toggle_ready_to_walk', as: 'dog_toggle_ready_to_walk'

  resources :dogs_park, only: %i[show new create]

  get "discover", to: "dogs#discover"


  resources :users, only: :show

  resources :parks, only: %i[index update create]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true
  validates :username, uniqueness: true
  validates :username, length: { in: 2..30 }
  has_many :dogs, dependent: :destroy
  has_one_attached :photo, dependent: :destroy

  # before_create :generate_code

  acts_as_reader

  # def generate_code
  #   self.code = SecureRandom.hex
  #   save
  # end
end

app/controllers/concerns/users_Controller.rb
class UsersController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @dogs = @user.dogs.order('name')

    @qrcode = RQRCode::QRCode.new("www.woof.network/dogs/#{@dogs.first.id}")

    @svg = @qrcode.as_svg(
      offset: 0,
      color: '000',
      shape_rendering: 'crispEdges',
      module_size: 4
    )
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to root_path
    else
      render 'pages/home'
    end
  end
end

app/views/users/show.html.erb
<%= render 'shared/navbar-top' %>
<div style="margin: 5rem 0px;" class="container">
  <div class="qr_codecontainer_one">
    <h2>Hello
      <%= @user.username %>
    </h2>
    <div class="qrcode">
      <%= @svg.html_safe  %>
    </div>
    <hr>
  </div>
  <div class="show_email"><span class="lighter_font_on_user_show">Email:</span><br>
    <%= @user.email %>
  </div>
  <div class="show_username"><span class="lighter_font_on_user_show">Username:</span><br>
    <%= @user.username %>
  </div>
  <hr>
  <div class="dogs_container_on_user">
    <% @dogs.each do |dog|  %>
      <ul class="user_page_show_list">
        <li>
          <div class="dog_name_on_user_show">
            <span class="lighter_font_on_user_show">My buddy:</span><br>
            <%= dog.name %>
          </div>
        </li>
        <li>
          <div class="dog_breed_on_user_show">
            <span class="lighter_font_on_user_show">Breed:</span><br>
            <%= dog.breed %>
          </div>
        </li>
      </ul>
      <hr>
      <div id="ready_to_walk_container">
        <ul class="user_page_show_list">
          <li>
            <%= simple_form_for(dog) do |f| %>
              <div class="custom-control custom-switch pl-3">
                <%= f.input :ready_to_walk, input_html: { id: "ready_to_walk_#{dog.id}", class: 'custom-control-input toggle' }, label_html: { id: "ready_to_walk_#{dog.id}", class: 'custom-control-label'}, label: ' '  %>
              </div>
            <% end %>
            <%= link_to 'Ready to walk', dog_toggle_ready_to_walk_path(dog),
                method: :patch,
                id: 'ready_to_walk',
                class: 'btn btn-secondary-revert d-none',
                remote: true %>
          </li>
          <li>
            <p class="mb-1" style=" color: #747474;">
              <%= "Change #{dog.name}'s home park" %>
              </p>
            <div class="park-selector d-flex align-items-center">
              <%= image_tag "tree_icon_60.png", alt: "Park", size: "30x30" %>
              <div class="dropdown ml-3">
                <%= simple_form_for(dog, remote: true, html: {class: "park-dropdown"}) do |f| %>
                  <%= f.association :parks, include_blank: false, label: false, input_html: { multiple: false } %>
                  <%= f.submit class: "d-none", id: "dog-submit-button" %>
                <% end %>
              </div>
            </div>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
  <%= render 'components/carousel_user_show' if @dogs.first.photos.attached? %>
  <ul class="user_page_show_list">
    <li>
      <%= link_to "Edit your profile", edit_user_registration_path, class: "btn btn-secondary my-3"  %>
    </li>
    <li>
      <%= link_to "Edit your dogs profile", edit_dog_path(@dogs.first), class: "btn btn-secondary my-3" %>
    </li>
    <li>
      <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-secondary-revert mb-3", id: "logout-btn" %>
    </li>
  </ul>
</div>
<%= render 'shared/bottom-navbar' %>