config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :users, only: %i[show] do
    resources :dogs, only: %i[new create]
  end

  resources :chatrooms, only: %i[show index] do
    resources :messages, only: :create
  end

  resources :sniffs, only: %i[index update destroy] do
    resources :chatrooms, only: :create
  end

  resources :dogs, only: [:show, :update, :destroy] do
    resources :sniffs, only: %i[create]
  end

  resources :dogs, only: :edit
  resources :users, only: :show

  patch 'dogs/:id/toggle_ready_to_walk', to: 'dogs#toggle_ready_to_walk', as: 'dog_toggle_ready_to_walk'

  resources :dogs_park, only: %i[show new create]

  get "discover", to: "dogs#discover"


  resources :users, only: :show

  resources :parks, only: %i[index update create]

end

app/views/shared/_bottom-navbar.html.erb
<% if user_signed_in? %>
  <nav class="navbar-bottom fixed-bottom navbar-dark bg-white">
    <div class="navbar-icons">
      <%= link_to root_path do %>
        <%= image_tag "icons8-dog-house-50#{'-filled' if current_page?(root_path)}.png", alt: "Home", size: "30x30" %>
      <% end %>
      <p>Home</p>
    </div>
    <div class="navbar-icons">
      <%= link_to discover_path do %>
        <%= image_tag "icons8-dog-bone-50#{'-filled' if current_page?(discover_path)}.png", alt: "Bone", size: "30x30" %>
      <% end %>
      <p>Discover</p>
    </div>
    <div class="navbar-icons">
      <%= link_to parks_path do %>
        <%= image_tag "icons8-country-50#{'-filled' if current_page?(parks_path)}.png", alt: "Map", size: "30x30" %>
      <% end %>
      <p>Parks</p>
    </div>
    <div class="navbar-icons">
      <%= link_to user_path(current_user) do %>
        <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, class: "avatar-medium" %>
        <% else %>
          <%= image_tag "user-icon-placeholder.png", class: "avatar-medium"%>
        <% end %>
      <% end %>
      <p>Profile</p>
    </div>
  </nav>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_modal.html.erb
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content modal-box">
      <div class="modal-header justify-content-center">
        <h5 class="modal-title" id="exampleModalLongTitle">Now it's time to add your dog!</h5>
      </div>
      <div class="modal-footer justify-content-center">
      <%= link_to "Continue",  new_user_dog_path(current_user), class: "modal-btn"  %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar-top-chatroom.html.erb
<nav class="navbar-top-dog-profile navbar fixed-top navbar-dark navbar-top d-flex">
  <div class="navbar-top-dog-profile-left d-flex align-items-center">
    <i style="font-size: 30px" class="fa fa-angle-left" aria-hidden="true" onclick="history.back(-1)"></i>
    <div class="navbar-top-dog-profile-left-logo">
      <h1 class="logo">
        <%= @dog_to_message.name %>
      </h1>
    </div>
  </div>
  <div class="navbar-top-dog-profile-right d-flex">
    <%= link_to sniffs_path do %>
      <%= image_tag "icons8-dog-heart-64.png", alt: "Dog heart", size: "30x30", class: "mr-2" %>
    <% end %>
    <%= link_to chatrooms_path do %>
      <%= image_tag "icons8-email-send-50.png", alt: "Send a message", size: "30x30", class: "mr-2"%>
    <% end %>
  </div>
</nav>

app/views/shared/_navbar-top-dog-profile.html.erb
<nav class="navbar-top-dog-profile navbar fixed-top navbar-dark navbar-top d-flex">
  <div class="navbar-top-dog-profile-left d-flex align-items-center">
    <i style="font-size: 30px" class="fa fa-angle-left" aria-hidden="true" onclick="history.back(-1)"></i>
    <div class="navbar-top-dog-profile-left-logo">
      <h1 class="logo">
        <%= @dog.name %>
      </h1>
    </div>
  </div>
  <div class="navbar-top-dog-profile-right d-flex">
    <%= link_to sniffs_path do %>
      <%= image_tag "icons8-dog-heart-64.png", alt: "Dog heart", size: "30x30", class: "mr-2" %>
    <% end %>
    <%= link_to chatrooms_path do %>
      <%= image_tag "icons8-email-send-50.png", alt: "Send a message", size: "30x30", class: "mr-2"%>
    <% end %>
  </div>
</nav>

app/views/shared/_navbar-top.html.erb
<% if user_signed_in? %>
<nav class="navbar fixed-top navbar-dark navbar-top" id="navbar">
  <%= link_to "Woof", root_path, id: "logo", class: "logo" %>
  <div class="menu-items d-flex">
    <div class="menu-items-sniffs">
      <%= link_to sniffs_path do %>
        <%= image_tag "icons8-dog-heart-64.png", alt: "Dog heart", size: "30x30", class: "mr-2" %>
      <% end %>
      <% unless @unread_sniffs.blank? %>
        <div class="red-dot">
        </div>
      <% end %>
    </div>
    <%= link_to chatrooms_path do %>
      <%= image_tag "icons8-email-send-50.png", alt: "Send a message", size: "30x30", class: "mr-2"%>
    <% end %>
  </div>
<% end %>
</nav>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", user_path(current_user), class: "dropdown-item"  %>
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>